### ISSUE TITLE
Error executing autogen.sh

### ISSUE THREAD

**Issue by hi-pablet** [CarloWood/libmemleak#3]
I've got the folloging error executing autogen.sh:

*ERROR:**********************************************************
* Using CW_DOXYGEN without arguments. Please specify directories to generate documtation in.
* Use a dot (.) for the root directory. For example:
* CW_DOXYGEN([. src utils])

Running on Ubuntu machine.

**Comment by AlericInglewood** [comment]
On Thu, 21 Feb 2019 05:52:33 -0800
hi-pablet <notifications@github.com> wrote:

> I've got the folloging error executing autogen.sh:
> 
> *ERROR:**********************************************************
> * Using CW_DOXYGEN without arguments. Please specify directories to
> generate documtation in.
> * Use a dot (.) for the root directory. For example:
> * CW_DOXYGEN([. src utils])
> 
> Running on Ubuntu machine.
> 

Thanks, that is indeed required in a newer version of cwm4.
I fixed on github.

https://github.com/CarloWood/libmemleak/commit/9a4056f3c7e4b0f3bc6ee3f2ab8b98a2791bd980

-- 
Carlo Wood <carlo@alinoe.com>

**Comment by CarloWood** [comment]
Assumed fixed.
