### ISSUE TITLE
Backtrace doesn't include the program symbols

### ISSUE THREAD

**Issue by fogroy1982** [CarloWood/libmemleak#5]
[libmemleak.tar.gz](https://github.com/CarloWood/libmemleak/files/3443007/libmemleak.tar.gz)
[libmemleak.tar.gz](https://github.com/CarloWood/libmemleak/files/3443008/libmemleak.tar.gz)

Hi Carlo,

I've tried your latest version (and also label 0.1.1) on my debian strectch computer,
compiling the hello program and testing, however when trying to see the back traces i get:

```
 #0  00007f6088264d96  in malloc at /home/rfogel/workspace/libmemleak2/src/memleak.c:1012
 #1  00005566120dba1a  in "hello"
 #2  00005566120dba9e  in "hello"
 #3  00007f60872614a4  in start_thread at /build/glibc-77giwP/glibc-2.24/nptl/pthread_create.c:456
 #4  00007f6086fa3d0f  in ?? at /build/glibc-77giwP/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:99
```

Where "hello" symbols are not correctly interpreted.

Setup info:
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.9.0-8-amd64
      Architecture: x86-64

Full reproduction steps (with the latest version):

sudo ln -s /usr/bin/libtoolize /usr/bin/libtool
sudo apt install git binutils binutils-dev libiberty-dev libreadline-dev doxygen
./autogen.sh
./configure
make
make install

On one terminal:
LD_PRELOAD='/usr/local/lib/libmemleak.so /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libbfd.so' ./hello

On another:
./memleak_control 
libmemleak> start

On the first terminal i see a backtrace named 46 and 
on the other terminal i do a dump command and i get a backtrace without the correct symbols
libmemleak> dump 46

```
 #0  00007f6088264d96  in malloc at /home/rfogel/workspace/libmemleak2/src/memleak.c:1012
 #1  00005566120dba1a  in "hello"
 #2  00005566120dba9e  in "hello"
 #3  00007f60872614a4  in start_thread at /build/glibc-77giwP/glibc-2.24/nptl/pthread_create.c:456
 #4  00007f6086fa3d0f  in ?? at /build/glibc-77giwP/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:99
```

Also note that with binutils-dev (2.25-5+deb8u1) it will be fixed and back trace will be shown correctly:

> libmemleak> dump 52
>  #0  00007fb2f182edee  in malloc at /home/rfogel/workspace/libmemleak_schroot/src/memleak.c:1012
>  #1  000000000040159f  in do_work(int) at /home/rfogel/workspace/libmemleak_schroot/src/hello.cc:156
>  #2  000000000040166e  in thread_entry1(void*) at /home/rfogel/workspace/libmemleak_schroot/src/hello.cc:19
>  #3  00007fb2f0bf0064  in start_thread
>  #4  00007fb2f092562d  in "libc-2.19.so"
>

**Comment by AlericInglewood** [comment]
Thank you for your bug report!

Things should probably start working again when you comment out this
line:

      range->begin = 0;

in src/addr2line.c

I'll push a fix later today.

Regards,
Carlo Wood

On Mon, 29 Jul 2019 08:33:03 -0700
fogroy1982 <notifications@github.com> wrote:

> [libmemleak.tar.gz](https://github.com/CarloWood/libmemleak/files/3443007/libmemleak.tar.gz)
> [libmemleak.tar.gz](https://github.com/CarloWood/libmemleak/files/3443008/libmemleak.tar.gz)
> 
> Hi Carlo,
> 
> I've tried your latest version (and also label 0.1.1) on my debian
> strectch computer, compiling the hello program and testing, however
> when trying to see the back traces i get:
> 
> ```
>  #0  00007f6088264d96  in malloc
> at /home/rfogel/workspace/libmemleak2/src/memleak.c:1012 #1
> 00005566120dba1a  in "hello" #2  00005566120dba9e  in "hello"
>  #3  00007f60872614a4  in start_thread
> at /build/glibc-77giwP/glibc-2.24/nptl/pthread_create.c:456 #4
> 00007f6086fa3d0f  in ??
> at /build/glibc-77giwP/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:99
> ```
> 
> Where "hello" symbols are not correctly interpreted.
> 
> Setup info:
>   Operating System: Debian GNU/Linux 9 (stretch)
>             Kernel: Linux 4.9.0-8-amd64
>       Architecture: x86-64
> 
> Full reproduction steps (with the latest version):
> 
> sudo ln -s /usr/bin/libtoolize /usr/bin/libtool
> sudo apt install git binutils binutils-dev libiberty-dev
> libreadline-dev doxygen ./autogen.sh
> ./configure
> make
> make install
> 
> On one terminal:
> LD_PRELOAD='/usr/local/lib/libmemleak.so /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libbfd.so' ./hello
> 
> On another:
> ./memleak_control 
> libmemleak> start  
> 
> On the first terminal i see a backtrace named 46 and 
> on the other terminal i do a dump command and i get a backtrace
> without the correct symbols
> libmemleak> dump 46  
> 
> 
> ```
>  #0  00007f6088264d96  in malloc
> at /home/rfogel/workspace/libmemleak2/src/memleak.c:1012 #1
> 00005566120dba1a  in "hello" #2  00005566120dba9e  in "hello"
>  #3  00007f60872614a4  in start_thread
> at /build/glibc-77giwP/glibc-2.24/nptl/pthread_create.c:456 #4
> 00007f6086fa3d0f  in ??
> at /build/glibc-77giwP/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:99
> ```
> 
> Also note that with binutils-dev (2.25-5+deb8u1) it will be fixed and
> back trace will be shown correctly:
> 
> > libmemleak> dump 52  
> >  #0  00007fb2f182edee  in malloc
> > at /home/rfogel/workspace/libmemleak_schroot/src/memleak.c:1012 #1
> > 000000000040159f  in do_work(int)
> > at /home/rfogel/workspace/libmemleak_schroot/src/hello.cc:156 #2
> > 000000000040166e  in thread_entry1(void*)
> > at /home/rfogel/workspace/libmemleak_schroot/src/hello.cc:19 #3
> > 00007fb2f0bf0064  in start_thread #4  00007fb2f092562d  in
> > "libc-2.19.so" 
> 
> 
> 



-- 
Carlo Wood <carlo@alinoe.com>

**Comment by CarloWood** [comment]
Pushed a new release (tag v1.0.2) as well as uploaded a new tar ball.
Please let me know if this for some reason does not fix it for you, but confident that it will, I'm now closing this issue.

**Comment by fogroy1982** [comment]
Verified, thanks

‫בתאריך יום ג׳, 30 ביולי 2019 ב-3:31 מאת ‪Carlo Wood‬‏ <‪
notifications@github.com‬‏>:‬
